### ISSUE TITLE
TypeError: decorator() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by BerserkerTroll** [tkem/cachetools#105]
I've tried to decorate an object method with `@func.ttl_cache` and then this method invocations started to yield the subj errors.
I've found `func.py` looking weird for me and I, like a true code macaque, rewrote it aping `tornado.gen.coroutine` style. Then it stopped giving me the error (haven't checked whether it is actually caching or not).

Is this an expected behaviour for an object method?

BTW, the code:
```python
def _cache(func, cache, typed=False):
    key = keys.typedkey if typed else keys.hashkey
    lock = RLock()
    stats = [0, 0]

    def cache_info():
        with lock:
            hits, misses = stats
            maxsize = cache.maxsize
            currsize = cache.currsize
        return _CacheInfo(hits, misses, maxsize, currsize)

    def cache_clear():
        with lock:
            try:
                cache.clear()
            finally:
                stats[:] = [0, 0]

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        k = key(*args, **kwargs)
        with lock:
            try:
                v = cache[k]
                stats[0] += 1
                return v
            except KeyError:
                stats[1] += 1
        v = func(*args, **kwargs)
        try:
            with lock:
                cache[k] = v
        except ValueError:
            pass  # value too large
        return v

    wrapper.__wrapped__ = func
    wrapper.cache_info  = cache_info
    wrapper.cache_clear = cache_clear
    return wrapper

def ttl_cache(func, maxsize=128, ttl=600, timer=time.time, typed=False):
    """Decorator to wrap a function with a memoizing callable that saves
    up to `maxsize` results based on a Least Recently Used (LRU)
    algorithm with a per-item time-to-live (TTL) value.
    """
    return _cache(func, TTLCache(maxsize, ttl, timer), typed)
```

**Comment by tkem** [comment]
I think it would make more sense to post your original code that triggered the exception here.

**Comment by BerserkerTroll** [comment]
Here it is:
```python
#!/usr/bin/python3

import time

from cachetools import func

class MWE:
	@func.ttl_cache
	def long_running_method(self, parameter):
		time.sleep(5)
		print(parameter)

	def method(self):
		self.long_running_method(42)

mwe = MWE()
mwe.method()
mwe.method()
```
```
$ python3 mwe.py 
Traceback (most recent call last):
  File "mwe.py", line 17, in <module>
    mwe.method()
  File "mwe.py", line 14, in method
    self.long_running_method(42)
TypeError: decorator() takes 1 positional argument but 2 were given
```

**Comment by tkem** [comment]
In your original code, replace
> @func.ttl_cache
with
> @func.ttl_cache()
or even better, something like
> @func.ttl_cache(maxsize=32, ttl=60)
or whatever fits your application.

Even if the default parameters are fine with you, you still have to "call" the decorator. The same with Python 3's `functools.lru_cache`, after which the `func` decorators are modelled.

**Comment by BerserkerTroll** [comment]
such a stupid mistake :man_facepalming:
