### ISSUE TITLE
3.0.0 Regression TypeError: <lambda>() missing 1 required positional argument: 'name' 

### ISSUE THREAD

**Issue by jaredkipe** [tkem/cachetools#119]
I'm no expert on the particulars here, if the API changed, or what is going on.  But here is are some traces after replacing cachetools==2.1.0 with 3.0.0

Thank you!
Jared

```
odoo_1   | Traceback (most recent call last):
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/tools/cache.py", line 84, in lookup
odoo_1   |     r = d[key]
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/tools/func.py", line 68, in wrapper
odoo_1   |     return func(self, *args, **kwargs)
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/tools/lru.py", line 44, in __getitem__
odoo_1   |     a = self.d[obj].me
odoo_1   | KeyError: ('ir.qweb', <function IrQWeb._get_asset_nodes at 0x7f31a946bd08>, 'web.assets_common', 'en_US', True, False, None, False, False, (1,))
odoo_1   | 
odoo_1   | During handling of the above exception, another exception occurred:
odoo_1   | 
odoo_1   | Traceback (most recent call last):
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
odoo_1   |     return compiled(self, append, new, options, log)
odoo_1   |   File "<template>", line 1, in template_website_layout_36
odoo_1   |   File "<template>", line 2, in body_call_content_35
odoo_1   |   File "<template>", line 19, in set_15
odoo_1   |   File "<decorator-gen-39>", line 2, in _get_asset_nodes
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/tools/cache.py", line 89, in lookup
odoo_1   |     value = d[key] = self.method(*args, **kwargs)
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 302, in _get_asset_nodes
odoo_1   |     return remains + asset.to_node(css=css, js=js, debug=debug, async_load=async_load)
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 154, in to_node
odoo_1   |     css_attachments = self.css() or []
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 311, in css
odoo_1   |     self.save_attachment("css", ' '.join(page), inc=idx)
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 258, in save_attachment
odoo_1   |     attachment = ira.sudo().create(values)
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/addons/base/ir/ir_attachment.py", line 466, in create
odoo_1   |     return super(IrAttachment, self).create(values)
odoo_1   |   File "/opt/odoo/hibou-suite/component_event/models/base.py", line 93, in create
odoo_1   |     record = super(Base, self).create(vals)
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/models.py", line 3380, in create
odoo_1   |     self._fields[key].determine_inverse(record)
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/fields.py", line 1071, in determine_inverse
odoo_1   |     getattr(records, self.inverse)()
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/odoo-11.0-py3.7.egg/odoo/addons/base/ir/ir_attachment.py", line 215, in _inverse_datas
odoo_1   |     super(IrAttachment, attach.sudo()).write(vals)
odoo_1   |   File "/opt/odoo/hibou-suite/component_event/models/base.py", line 103, in write
odoo_1   |     self._event('on_record_write').notify(record, fields=fields)
odoo_1   |   File "/opt/odoo/hibou-suite/component_event/models/base.py", line 89, in _event
odoo_1   |     return collecter.collect_events(name)
odoo_1   |   File "/opt/odoo/hibou-suite/component_event/components/event.py", line 263, in collect_events
odoo_1   |     events = self._init_collected_events(self._collect_events(name))
odoo_1   |   File "/usr/local/lib/python3.7/site-packages/cachetools-3.0.0-py3.7.egg/cachetools/__init__.py", line 82, in wrapper
odoo_1   |     k = key(*args, **kwargs)
odoo_1   | TypeError: <lambda>() missing 1 required positional argument: 'name'
```

**Comment by jaredkipe** [comment]
Thank you, I'm sure you are correct.  I'll pass the needed information along to the particular module's maintainer.
