### ISSUE TITLE
AttributeError if reimplementing expire method

### ISSUE THREAD

**Issue by alex-eri** [tkem/cachetools#201]
Trying

```
import cachetools
from cachetools.cache import Cache

class ExpireCache(cachetools.TTLCache):
    def __init__(self, maxsize, ttl, on_expire=[]):
         self.on_expire = on_expire
         cachetools.TTLCache.__init__(self, maxsize, ttl)
         
    def expire(self, time=None, cache_getitem=Cache.__getitem__):
        """Remove expired items from the cache."""
        if time is None:
            time = self.__timer()
        root = self.__root
        curr = root.next
        links = self.__links
        cache_delitem = Cache.__delitem__
        while curr is not root and curr.expire < time:
            v = cache_getitem(self, curr.key)
            for cb in self.on_expire:
              cb(v)
            cache_delitem(self, curr.key)
            del links[curr.key]
            next = curr.next
            curr.unlink()
            curr = next
            
def on_e(i):
    print(i)

EC =  ExpireCache(1<<10, 1, on_expire=[on_e])
EC[1] = 2
print(EC[1])
import time
time.sleep(10)
EC[1] = 3
```

I have this Traceback

```
Traceback (most recent call last):
  File "/home/eri/Projects/2021/hellowords/cachetool.py", line 31, in <module>
    EC[1] = 2
  File "/home/eri/.local/lib/python3.9/site-packages/cachetools/ttl.py", line 88, in __setitem__
    self.expire(time)
  File "/home/eri/Projects/2021/hellowords/cachetool.py", line 13, in expire
    root = self.__root
AttributeError: 'ExpireCache' object has no attribute '_ExpireCache__root'

```

**Comment by tkem** [comment]
Please see https://docs.python.org/3.9/tutorial/classes.html#private-variables.

You cannot access members starting with double underscores in subclasses. The reason I made these "private" is that I reserve the right to change these without notice, so you shouldn't use these in the first place.
