### ISSUE TITLE
mapping doesn't handle dict as an input arg

### ISSUE THREAD

**Issue by cseager** [tkem/cachetools#28]
When trying to use a cache on a function that accepts dict args, an error is raised because dict is not hashable. 

```
>>> import cachetools
>>> @cachetools.ttl_cache(maxsize=1, ttl=1)
... def whatever(a, b):
...     pass
...
>>> whatever({1:"A"}, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cachetools/decorators.py", line 39, in wrapper
    result = cache[key]
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cachetools/ttlcache.py", line 69, in __getitem__
    link = cache_getitem(self, key)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cachetools/cache.py", line 39, in __getitem__
    return self.__mapping[key][0]
TypeError: unhashable type: 'dict'
```

**Comment by icecraft** [comment]
@tkem may be we can use  pickle.dumps the args and kwargs to get a hashlib object.

**Comment by tkem** [comment]
@icecraft: You can do whatever you want by providing a custom `key` function: https://pythonhosted.org/cachetools/#key-functions
