### ISSUE TITLE
Support for decorating coroutines

### ISSUE THREAD

**Issue by deceze** [tkem/cachetools#92]
The memoization decorators could use support for coroutines:

```python
@cachetools.cached(cache={})
async def foo():
    pass
```

Currently this caches the coroutine itself, which can only be awaited once and will produce an error when awaited again.

**Comment by tkem** [comment]
Interesting idea! So far, I haven't had too much experience with `async`, so could you elaborate on that?
Anyway, I think a separate decorator (`cachedasync`?) might be preferable.

**Comment by deceze** [comment]
Yes, something like `asynccached` or so might be preferable, though it's probably possible  to add support for awaitables into the current implementation without many problems.

In a nutshell, when an `async def` function is called it returns a coroutine object, not its actual result. This coroutine object needs to be `await`ed, which will yield its actual return value. However, it can only be awaited once:

```python
>>> async def foo():
...     return 'bar'
>>> f = foo()
>>> f
<coroutine object foo at 0x10f61e938>
>>> import asyncio 
>>> r = asyncio.get_event_loop().run_until_complete(f)
>>> r
'bar'
>>> asyncio.get_event_loop().run_until_complete(f)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
RuntimeError: cannot reuse already awaited coroutine
```

`cached` currently isn't aware of that and caches the coroutine object, which works only once and fails the second time. It would need to be aware that the value is an awaitable, `await` its result and only cache that.

**Comment by tkem** [comment]
Thanks for elaborating, and especially a concise example.
Based on the little I know about async functions, I assumed something similar.
I'll think about it. However, I tend to prefer a dedicated `asynccached` decorator, especially since e.g. Python 3.6's `functools.lru_cache` doesn't handle async functions specially, either.

**Comment by tkem** [comment]
@deceze: I did quick prototype of a `@cachedasync` decorator:
https://github.com/tkem/cachetools/tree/wip/async
It's far from complete and largely untested, but maybe you'd like to take a look.

**Comment by deceze** [comment]
I had a quick look, and yes, it generally looks good. The decorator just needs the added `async` keyword, and it needs to `await` the wrapped call; looks like you've covered all that. You might want to consider using `inspect.isawaitable`, maybe just in an `assert`, to ease debugging in case of misuse.

**Comment by tkem** [comment]
Thanks! I was thinking about using `assert` to prevent passing a "plain" function to the decorator, too. But this is still a long way from "production-ready"...

**Comment by vomindoraan** [comment]
Any progress on this? We could really use an async LFU cache decorator in our current project.

**Comment by tkem** [comment]
@vomindoraan: No, I'm still wondering if I should take the burden of supporting this - especially since I've never used any of the `async` stuff myself.
Anything wrong with using the `@cachedasync` decorator from https://github.com/tkem/cachetools/tree/wip/async in your project? Or even better, improve on that and publish it as a separate module yourself!

**Comment by tkem** [comment]
Another (minor) issue would be that `async` is only available in Python >= 3.5, and I still want `cachetools` to be compatible with Python 2.7 for the foreseeable future. [Namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/) might help here, but I'm not sure it's worth the effort.

**Comment by Galarzaa90** [comment]
Is there any update on this? I was really excited when I found this library, but I only needed it on coroutines :(

**Comment by thiswillbeyourgithub** [comment]
For anyone else wondering this in 2024 I stumbled upon this: https://github.com/iamsinghrajat/async-cache


Example in their README:

``` python
# LRU Cache
from cache import AsyncLRU

@AsyncLRU(maxsize=128)
async def func(*args, **kwargs):
    """
    maxsize : max number of results that are cached.
              if  max limit  is reached the oldest result  is deleted.
    """
    pass


# TTL Cache
from cache import AsyncTTL

@AsyncTTL(time_to_live=60, maxsize=1024, skip_args=1)
async def func(*args, **kwargs):
    """
    time_to_live : max time for which a cached result  is valid (in seconds)
    maxsize : max number of results that are cached.
              if  max limit  is reached the oldest result  is deleted.
    skip_args : Use `1` to skip first arg of func in determining cache key
    """
    pass

```
